version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: docker-movie
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      backendme:
        ipv4_address: 172.27.0.2
    command: ifconfig
  db:
    container_name: movie-mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=movie-xsis
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backendme:
        ipv4_address: 172.27.0.3

volumes:
  db:
    driver: local

networks:
  backendme:
    driver: bridge
    ipam:
      driver: default
      config:
        -  subnet: 172.27.0.0/16