definitions:
  payload.CreateMoviePayload:
    properties:
      description:
        type: string
      image:
        type: string
      rating:
        type: number
      title:
        type: string
    required:
    - description
    - rating
    - title
    type: object
  payload.MoviePayload:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      rating:
        type: number
      title:
        type: string
      updated_at:
        type: string
    type: object
  payload.UpdateMoviePayload:
    properties:
      description:
        type: string
      image:
        type: string
      rating:
        type: number
      title:
        type: string
    required:
    - description
    - rating
    - title
    type: object
  web.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  web.Response:
    properties:
      data: {}
      errors:
        items:
          $ref: '#/definitions/web.ErrorResponse'
        type: array
    type: object
info:
  contact:
    email: rasyidmaulidmajid@gmail.com
    name: rasyid
  description: This is a backend service for movie-xsis
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: movie-xsis
  version: "1.0"
paths:
  /v1/movie:
    post:
      description: Endpoint for Create Movie
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payload.CreateMoviePayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Create Movie
      tags:
      - Movie
  /v1/movie/{id}:
    delete:
      description: Endpoint for Delete Movie by id
      parameters:
      - description: id of movie
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Delete Movie by id
      tags:
      - Movie
    get:
      description: Endpoint for Get Movie by id
      parameters:
      - description: id of movie
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.MoviePayload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Get Movie by ids
      tags:
      - Movie
    patch:
      description: Endpoint for Update Movie
      parameters:
      - description: id of movie
        in: path
        name: id
        required: true
        type: string
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/payload.UpdateMoviePayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update Movie
      tags:
      - Movie
  /v1/movie/like:
    get:
      description: Endpoint for  Get Movie By Like
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/payload.MoviePayload'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Get Movie By Like
      tags:
      - Movie
  /v1/movies:
    get:
      description: Endpoint for Get Movies
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/payload.MoviePayload'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Get Movies
      tags:
      - Movie
swagger: "2.0"
